[versions]
agp = "9.3.3"
android-compileSdk = "37"
android-compileSdkMinor = "2"
android-minSdk = "24"
android-targetSdk = "37"
kotlin = "2.4.21"

# Androidx
androidx-activity = "1.13.0"
androidx-lifecycle = "2.11.0"
androidx-datastore = "1.3.0-alpha11"
androidx-room3 = "3.0.3"
androidx-navigation3 = "1.2.0"
androidx-media3 = "1.11.1"
androidx-glance = "1.3.0-alpha02"

# Compose/UI
compose = "1.13.0-beta01"
material3 = "1.5.0-beta01"
#noinspection GradleDependency,NewerVersionAvailable do not update this to alpha05 it makes the detail pane always visible
material3-adaptive = "1.3.0-alpha04"

# Compose 3rd party
kmpalette = "3.1.0"

# Networking
ktor = "3.6.0"
coil = "3.6.3"

# Misc
koin = "4.2.2"

[libraries]
# Compose
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-adaptive-nav = { module = "androidx.compose.material3.adaptive:adaptive-navigation3", version.ref = "material3-adaptive" }
compose-material3-windowSize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

# Androidx
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics", version = "1.12.1" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version = "2.7.1" }
androidx-room3-runtime = { module = "androidx.room3:room3-runtime", version.ref = "androidx-room3" }
androidx-room3-compiler = { module = "androidx.room3:room3-compiler", version.ref = "androidx-room3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-media3-ktor = { module = "androidx.media3:media3-datasource-ktor", version.ref = "androidx-media3" }
androidx-media3-decoder-ffmpeg = { module = "androidx.media3:media3-decoder-ffmpeg", version.ref = "androidx-media3" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.11.0" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
androidx-browser = { module = "androidx.browser:browser", version = "1.10.0" }

# Kotlinx
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.8.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.11.0" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.5.2" }

# Networking
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }

# Compose 3rd party
capsule = { module = "top.ltfan.capsule:capsule", version = "1.2.0" }
kmpalette-core = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }
kmpalette-network = { module = "com.kmpalette:extensions-network", version.ref = "kmpalette" }
materialKolor = { module = "com.materialkolor:material-kolor", version = "5.0.1" }
composePipette = { module = "dev.zt64.compose.pipette:compose-pipette", version = "2.0.0" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings-no-arg", version = "1.3.0" }

# Misc
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
subsonicKotlin = { module = "dev.zt64.subsonic:subsonic-client", version = "1.0.0-beta08-SNAPSHOT" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }
antisocialcord = { module = "com.github.Nightdavisao:antisocialcord-kt", version = "master-SNAPSHOT" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.9" }
androidx-room3 = { id = "androidx.room3", version.ref = "androidx-room3" }
